version: "3.7"
services:
  service-1:
    build: /home/student/NBSMentoredChallenge/service-1/Dockerfile
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  service-2:
    build: /home/student/NBSMentoredChallenge/service-2/Dockerfile
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  service-3:
    build: /home/student/NBSMentoredChallenge/service-3/Dockerfile
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
  service-4:
    build: /home/student/NBSMentoredChallenge/service-4/Dockerfile
    ports:
    - target: 5003
      published: 5003
      protocol: tcp



      
